### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by Sagar19RaoRane** [kanch231004/News-Feed#3]
A problem occurred evaluating project ':app'.
> Cannot set the value of read-only property 'sourceDirectories' for task ':app:fullCoverageReport' of type org.gradle.testing.jacoco.tasks.JacocoReport.

**Comment by kanch231004** [comment]
Hi Sagar, apologies for the oversight of the issue raised.
Is this resolved?

**Comment by kanch231004** [comment]
Closing this as there is no further comment.
